### ISSUE TITLE
Create STIX Store microservice (cti-stix-store)

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/unfetter-discover#104]
Create a Microservice that supports GET/POST/PUT/DELETE of STIX objects. 

- Properly support custom objects
- Properly support custom properties
- Wrap into docker container
- Microservice should incorporate easy query.
- Incorporate file loading to prepopulate data.

**Comment by exceptionfactory** [comment]
Created initial [cti-stix-store](https://github.com/iadgov/cti-stix-services) with Docker and Docker Compose configurations as well as support for configurable schema definitions.
