### ISSUE TITLE
Create STIX discover Microservice (cti-stix-discover)

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/unfetter-discover#105]
Create a microservice that calls the cti-stix-store to retrieve more complicated groups of STIX objects.  This is a stateless microservice and relies on the cti-stix-store

**Comment by exceptionfactory** [comment]
Completed and merged initial version of [cti-stix-discover](https://github.com/iadgov/cti-stix-services/tree/master/cti-stix-discover) under cti-stix-services repository.
