### ISSUE TITLE
Implement Continous Integration

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/unfetter-discover#110]
Implement the basics for continous integration that supports code testing, syntax checking, source code evaluation, documentation building

Build initial capability for evaluation

**Comment by exceptionfactory** [comment]
Initial Continuous Integration server should run [Jenkins](https://jenkins.io) with the [NodeJS Plugin](https://wiki.jenkins-ci.org/display/JENKINS/NodeJS+Plugin).  StrongLoop has some articles on this [configuration](https://strongloop.com/strongblog/roll-your-own-node-js-ci-server-with-jenkins-part-1/) that are a little dated, but provide the basics.  Jenkins also has a [Checkstyle Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Checkstyle+Plugin) that can be used to evaluate code formatting based on Checkstyle XML generated from an [ESLint](http://eslint.org/docs/user-guide/formatters/) configuration.
