### ISSUE TITLE
Evaluate Restify to determine if it should be used

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/unfetter-discover#116]
We are using Express for Unfetter. However, restify might be a better option for just the services that require rest interfaces.  Evaluate and lets determine if we should change software.

**Comment by exceptionfactory** [comment]
It also may be worth taking another look at [Loopback](http://loopback.io/) or [Sails.js](http://sailsjs.org/).  Both build on Express and provide more opinionated implementations with less code for things like authorization and database connections.  One framework might be a better fit for the STIX Data Object services, and another might be a better fit for the customized Unfetter Discover layer.

**Comment by exceptionfactory** [comment]
The [Loopback](http://loopback.io/) framework provides a non-database specific model definition format that automates both the publishing of REST services and the generation of Swagger definitions.  The initial version of cti-stix-store builds on Loopback and leverages the JSON Schema parsing services from unfetter-discover-api to automate the model definition process.
