### ISSUE TITLE
Research need for rest service discovery

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/unfetter-discover#123]
Do we need a tool like Console, Registrator, or something similiar to support registering and discovery of rest services?  Or is this too complicated for our efforts.

http://howtocookmicroservices.com/docker-compose/

**Comment by infosec-alchemist** [comment]
Consider just using the built in Docker DNS discovery since that will reduce the code that people have to download and run locally to try out the project 

https://docs.docker.com/engine/userguide/networking/configure-dns/

**Comment by infosec-alchemist** [comment]
NGINX and docker-gen implement the virtual hosting that we needed.  For now, we don't seem to need additional service discovery, unless we are supporting operational systems.

**Comment by exceptionfactory** [comment]
DNS resolution based on container names provides basic service discovery for containers created through Docker Compose.
