### ISSUE TITLE
research  Nginx instead of Apache

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/unfetter-discover#132]
Nginx seems to be a popular choice as a proxy for Docker container.  Quickly look at Nginx and see if it makes sense to move to it.

This is one example of people using Nginx for that front end.
https://www.airpair.com/docker/posts/efficiant-development-workfow-using-git-submodules-and-docker-compose

**Comment by exceptionfactory** [comment]
It should be fairly straightforward to switch from Apache to Nginx with a basic reverse proxy configuration that supports SSL connections.  The Nginx configuration will need to implement the equivalent of the Apache configuration: https://github.com/iadgov/unfetter-discover/blob/master/resources/httpd-unfetter.conf

**Comment by infosec-alchemist** [comment]
NGINX seems to be working with reverse proxy using docker-gen.
