### ISSUE TITLE
Swagger must reflect the URL for the cti-stix-store

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/unfetter-discover#140]
The CTI-STIX-STORE has a virtual_host in the docker-compose.yml.  The SWAGGER application should reflect that for the "try it" functionality.

**Comment by exceptionfactory** [comment]
The most recent version of cti-stix-store generates a Swagger Specification that does not include a specific URL, so the Swagger UI works without any additional configuration when interacting with cti-stix-store.
