### ISSUE TITLE
Change from Stix object names to more descriptive names in UI

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/unfetter-discover#147]
In the UI, use more descriptive words for the names of objects than just STIX.

Reports will be "Survey"
"Attack Pattern" will be "Techniques"
"Course of Action" will be "Critical Controls"

**Comment by exceptionfactory** [comment]
These labels may provide closer association to the current example sources of MITRE ATT&CK and the Center for Internet Security, but they also narrow the focus of the application versus keeping it open to following the STIX terminology.  This may be useful when it comes to the Unfetter Discover application if the intention is to localize the terminology versus following the official definitions.

**Comment by exceptionfactory** [comment]
It is also worth noting that some portions of the current user interface present labels directly from the STIX type information, so it would require a good deal of labeling lookups in order to systemically change the terminology.
