### ISSUE TITLE
Can't get swagger json from cti-stix-ui when running unfetter-discover

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/unfetter-discover#160]
When running unfetter-discover, and opening the CTI-STIX-UI, I can't get to the swagger definitions at cti-stix-store-api.

Going to:
https://localhost/cti-stix-store-api/specifications/

Receive this message:
{"errors":[{"status":404,"source":"","title":"Error","code":"","detail":"Cannot GET /explorer/"}]}

**Comment by exceptionfactory** [comment]
You may be referencing an older version of cti-stix-store. The latest version of cti-stix-store works when attempting to view the API specification using https://localhost/cti-stix-store-api/specifications/ after launching unfetter-discover using docker-compose.

**Comment by exceptionfactory** [comment]
Corrected Nginx proxy configuration after reevaluating and determining that additional location setting was not necessary now that Swagger specification is available under the primary location context configuration.  Corrected in Pull Request #161.
