### ISSUE TITLE
Investigate building the UI on top of cti-stix-ui

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/unfetter-discover#180]
unfetter-discover-ui does not include the STIX admin pages, so both the cti-stix-ui and unfetter-discover-ui are necessary to support a user interface.

However, much of the backend software is duplicate.  Therefore, research and implement a way to have unfetter-discover-ui be an additive container on top of the cti-stix-ui code.  Likely, find a way to add the unfetter-discover-ui code to cti-stix-ui.

**Comment by exceptionfactory** [comment]
[Ember Engines](https://github.com/dgeb/ember-engines) might be one potential solution for building separate applications that we can compose together.

**Comment by infosec-alchemist** [comment]
Okay, I'm going to assign this to you.  It will certainly make our dev a bit easier.   If its too much work or would limit our UI, then we can pass on it.

**Comment by infosec-alchemist** [comment]
We could also consider overwriting and adding to the CTI-STIX-UI container.
