### ISSUE TITLE
Investigate STIX 2.0 schemas from johnwunder/stix2.0

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/unfetter-discover#46]
Look at these schema's, determine if we should use their schemas or augment with our own.
https://github.com/johnwunder/stix2.0

**Comment by exceptionfactory** [comment]
These STIX 2.0 Schema objects are complete and reflect the current Release Candidate 2 version.  The current schemas in unfetter-discover-api do not contain all of the STIX 2.0 properties, and also use a relative definition for $ref properties as opposed to the relative file path format used in these schemas.  The SchemaService (https://github.com/iadgov/unfetter-discover/blob/master/unfetter-discover-api/src/services/schema.js) could be refactored to handle these relative path schema references with some work using the json-schema-ref-parser.

Leveraging these schemas in a dynamic fashion would require implementing the ability retrieve them from GitHub prior to starting the application.  If these schemas were published in a canonical location, that would be a better path for integration.
