### ISSUE TITLE
Provide input validation for the URL field under "External References" when adding new data element

### ISSUE THREAD

**Issue by McDev10** [iadgov/unfetter-discover#59]
Current form allows for invalid URL's to be entered

**Comment by exceptionfactory** [comment]
The unfetter-discover-api implementation for the External Reference url field is already performing validation.

**Comment by infosec-alchemist** [comment]
Lets look at Browser side validation with visual cues when the data is entered so the user knows that the URL is valid or not while they are typing.  But, we can push this off until after Sept 30th, unless we have time.
